### ISSUE TITLE
plugin shows empty list when launched

### ISSUE THREAD

**Issue by jape42** [Heckie75/kodi-addon-bbc-podcasts#2]
Is this content geo locked?  When I launch this I end up with an empty list containing only "..". I'm using 19.3 on pi3b+, raspbian bullseye.
 
[bbc.txt](https://github.com/Heckie75/kodi-addon-bbc-podcasts/files/7971151/bbc.txt)

**Comment by Heckie75** [comment]
Same here, I guess that BBC changed its website again so that screen scraping does not work anymore. 

It is really hard to stay up to date if there are changes. Maybe I have time to take a look at it later.

**Comment by Heckie75** [comment]
@jape42 

I have changed the parser. May be you yould like to test the addon (see zip archive)

**Comment by jape42** [comment]
Tried out the zip.  Was able to play 2 podcasts.  Many thanks.
